### ISSUE TITLE
emacs 25: lock up with gui dialog boxes

### ISSUE THREAD

**Issue by Jehops** [bburns/clipmon#3]
Please see http://debbugs.gnu.org/cgi/bugreport.cgi?bug=22214.  Since I'm unsure if this is a problem in Emacs 25 or clipmon (or both) I copy the debbug report here.

Regards,

Joseph

**Comment by bburns** [comment]
Hi Joseph, thanks for the bug report and recipe - it seems to be a problem on Linux as it works okay on Windows - I'd just built 25.0.50.1 also. But apparently `x-get-selection-value` is obsolete in 25 - I'll need to update it to use `gui-get-primary-selection`. 

I won't be able to test it until I set up a Linux VM, but that's something I've been needing to do also. 

Regards, 
Brian

**Comment by emanresusername** [comment]
@bburns has there been any movement on this one? I just moved up to 25.1 and I'm getting
`Symbol’s function definition is void: x-selection-owner-p`
now 😢

**Comment by bburns** [comment]
Hi, thanks for the report - is this related to the gui dialog box lockup? If not I created a new issue here - https://github.com/bburns/clipmon/issues/9

I've got a Linux VM setup but am not getting that error with 25.1 - more details there. 

Regarding the gui dialog lockup - it bit me while testing 25.1 - but now I've got a VM setup and can see if I can make any progress on it.

**Comment by emanresusername** [comment]
@bburns [my issue here is resolved with the latest push](http://who-is-awesome.com) #13

**Comment by obar** [comment]
For the longest time I didn't realize this bug was caused by clipmon, which is a very useful package for me. I tried compiling with very up-to-date gtk in case there was a but with that. At the moment I'm not loading clipmon and I was missing it. I have a little solution below that works for my use case.

I wasn't using auto insert, just using clipmon to have emacs get everything from the system clipboard into the kill ring. My new way of doing this has been working well so I'm sharing it here:

Install [CopyQ](https://github.com/hluk/CopyQ). Create an automatic command called SendToEmacs, with the command:

```
bash: emacsclient --no-wait --eval "(current-kill 0 'do-not-move)"
```
Under this command's Advanced tab, set this to an automatic action (happens every time text is copied) and set it to match all text/plain formatted items with the content `.*`

This doesn't use the clipmon package.

--------------------------

Instead that eval in the CopyQ command above could be to run `clipmon--check-clipboard` and have the timers disabled, if someone wanted the auto insert clipmon functionality (some timer-removing modifications to the package would be required).

Another option to use clipmon without CopyQ and without emacs timers would be to subscribe to dbus events of clipboard changes. I believe klipper, gpaste, or similar as a WM clipboard manager could provide those necessary signals.

**Comment by mandarm** [comment]
Just wanted to confirm, in case it is useful to anyone else facing this problem with clipmon, that as of July 2023, the problem persists. @obar's suggestion re: copyq provides the only workable alternative that I've been able to find. It is also simple and effective. Thank you, @obar!
